services:
  - type: web
    name: todoapp
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    branch: main
    plan: free
